#!/bin/zsh

# Compare Humdrum import vs Humdrum export/reimport (fileList)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallHumImportVsHumExport.py ~/Documents/test/teststuff/fileList.txt"'

# Compare Humdrum import vs verovio convert to MEI then MEI import (fileList2)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallHumVsMeiImport.py ~/Documents/test/teststuff/fileList2.txt"'

# Verovio convert Humdrum to MEI, then compare MEI import vs MEI export/reimport (fileList3)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallHumVerovioVsMeiExport.py ~/Documents/test/teststuff/fileList3.txt"'

# Compare Humdrum import vs MEI export/reimport (fileList4)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallHumImportVsMeiExport.py ~/Documents/test/teststuff/fileList4.txt"'

# Compare MusicXML import vs MEI export/reimport (fileList5)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMusicXMLImportVsMeiExport.py ~/Documents/test/teststuff/fileList5.txt"'

# Compare MusicXML import vs Humdrum export/reimport (fileList6)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMusicXMLImportVsHumdrumExport.py ~/Documents/test/teststuff/fileList6.txt"'

# Compare MusicXML import vs MusicXML export/reimport (fileList7)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMusicXMLImportVsMusicXMLExport.py ~/Documents/test/teststuff/fileList7.txt"'

# Compare Humdrum import vs MusicXML export/reimport (fileList8)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallHumImportVsMusicXMLExport.py ~/Documents/test/teststuff/fileList8.txt"'

# Compare MEI import vs MusicXML export/reimport (fileList9)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMeiImportVsMusicXMLExport.py ~/Documents/test/teststuff/fileList9.txt"'

# Compare ABC import vs MusicXML export/reimport (fileList10)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallABCImportVsMusicXMLExport.py ~/Documents/test/teststuff/fileList10.txt"'

# Compare ABC import vs Humdrum export/reimport (fileList11)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallABCImportVsHumdrumExport.py ~/Documents/test/teststuff/fileList11.txt"'

# Compare ABC import vs MEI export/reimport (fileList12)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallABCImportVsMeiExport.py ~/Documents/test/teststuff/fileList12.txt"'

# Compare ABC import vs ABC export/reimport (fileList13)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallABCImportVsABCExport.py ~/Documents/test/teststuff/fileList13.txt"'

# Verovio convert ABC to MEI, then compare MEI import vs MEI export/reimport (fileList14)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallABCVerovioVsMeiExport.py ~/Documents/test/teststuff/fileList14.txt"'

# Compare ABC import vs verovio convert ABC to MEI then MEI import (fileList15)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallABCVsMeiImport.py ~/Documents/test/teststuff/fileList15.txt"'

# Compare MusicXML import vs ABC export/reimport (fileList16)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMusicXMLImportVsABCExport.py ~/Documents/test/teststuff/fileList16.txt"'

# Compare MEI import vs ABC export/reimport (fileList17)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMeiImportVsABCExport.py ~/Documents/test/teststuff/fileList17.txt"'

# Compare Humdrum import vs ABC export/reimport (fileList18)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallHumImportVsABCExport.py ~/Documents/test/teststuff/fileList18.txt"'

# Compare multiscore import vs MEI export to multiple <mei> (fileList19)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMultiscoreVsMei_MultiMei.py ~/Documents/test/teststuff/fileList19.txt"'

# Compare multiscore import vs MEI export to multiple <mdiv> (fileList20)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMultiscoreVsMei_MultiMdiv.py ~/Documents/test/teststuff/fileList20.txt"'

# Compare multiscore import vs MEI export to multiple <music> (fileList21)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMultiscoreVsMei_MultiMusic.py ~/Documents/test/teststuff/fileList21.txt"'

# Compare MEI v4 import vs MEI export/reimport (fileListMei)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMeiImportVsMeiExport.py ~/Documents/test/teststuff/fileListMei.txt"'

# Compare MEI v5 import vs MEI export/reimport (fileListMei5)
osascript -e 'tell app "Terminal" to activate' -e 'tell app "Terminal" to do script "cd ~/Documents/Code/converter21; python3 tests/diffallMeiImportVsMeiExport.py ~/Documents/test/teststuff/fileListMei5.txt"'

